import dns from 'dns';
import { promisify } from 'util';

const resolveMx = promisify(dns.resolveMx);

// Common disposable/throwaway email domains
const DISPOSABLE_DOMAINS = new Set([
  'mailinator.com', 'guerrillamail.com', 'guerrillamail.net', 'guerrillamail.org',
  'guerrillamail.biz', 'guerrillamail.de', 'guerrillamail.info', 'spam4.me',
  'trashmail.com', 'trashmail.me', 'trashmail.net', 'trashmail.at', 'trashmail.io',
  'tempmail.com', 'temp-mail.org', 'temp-mail.io', 'throwam.com', 'throwam.com',
  'yopmail.com', 'yopmail.fr', 'cool.fr.nf', 'jetable.fr.nf', 'nospam.ze.tc',
  'nomail.xl.cx', 'mega.zik.dj', 'speed.1s.fr', 'courriel.fr.nf', 'moncourrier.fr.nf',
  'monemail.fr.nf', 'monmail.fr.nf', 'fakeinbox.com', 'mailnull.com', 'spamgourmet.com',
  'spamgourmet.net', 'spamgourmet.org', 'spamgourmet.com', 'spamgourmet.net',
  'sharklasers.com', 'guerrillamailblock.com', 'grr.la', 'guerrillamail.info',
  'spam4.me', 'dispostable.com', 'mailnesia.com', 'mailnull.com',
  'spamfree24.org', 'spamfree24.de', 'spamfree24.eu', 'spamfree24.info',
  'spamfree24.net', 'spamfree24.com', 'spamfree.eu', 'spamspot.com',
  'maildrop.cc', 'tempr.email', 'discard.email', 'discardmail.com', 'discardmail.de',
  'spamgourmet.com', 'throwam.com', 'objectmail.com', 'obobbo.com',
  'mail-temp.com', 'mytempemail.com', 'emailtemporanea.net', 'emailtemporanea.com',
  'getnada.com', 'getairmail.com', 'filzmail.com', 'cfl.fr', 'courrieltemporaire.com',
  'jetable.com', 'jetable.net', 'jetable.org', 'nomail.pw', 'nowmymail.com',
  'spamfree.eu', 'mailexpire.com', 'mailforspam.com', 'spamhereplease.com',
  'mailscrap.com', 'spammotel.com', 'spamoff.de', 'tradermail.info',
  'tempinbox.com', 'tempinbox.co.uk', 'spamify.com', 'binkmail.com',
  'bob.email', 'boxtemp.com.br', 'brasx.org', 'breakthru.com', 'brefmail.com',
  'broadbandninja.com', 'buffemail.com', 'bugmenot.com', 'bulkbye.com',
  'bumpymail.com', 'byom.de', 'cachedot.net', 'calculator.com', 'camidge.com',
  'casualdx.com', 'cek.pm', 'cellurl.com', 'centermail.com', 'centermail.net',
  'chammy.info', 'cheatmail.de', 'chewiemail.com', 'childsavetrust.org',
  'chogmail.com', 'clixser.com', 'cmail.com', 'cmail.net', 'cmail.org',
  'coieo.com', 'composemew.com', 'consumerriot.com', 'cool.fr.nf',
  'correo.blogos.net', 'cosmorph.com', 'courriel.fr.nf', 'courrieltemporaire.com',
  'coverme.com', 'crapmail.org', 'crazymailing.com', 'cust.in',
  'dacoolest.com', 'daemsteam.com', 'daintly.com', 'damnthespam.com',
  'deadaddress.com', 'deadletter.ga', 'deagot.com', 'dealja.com',
  'despam.it', 'despammed.com', 'devnullmail.com', 'dingbone.com',
  'diredmail.com', 'discard.ga', 'discard.gq', 'discard.ml', 'discard.tk',
  'discardmail.de', 'disposableaddress.com', 'disposableemailaddresses.com',
  'disposableinbox.com', 'dispose.it', 'dm.w3internet.co.uk', 'dodgeit.com',
  'dodgemail.de', 'dodgit.com', 'donemail.ru', 'dontreg.com', 'dontsendmespam.de',
  'drdrb.com', 'drdrb.net', 'dump-email.info', 'dumpandfuck.com', 'dumpmail.de',
  'dumpyemail.com', 'duskmail.com', 'e4ward.com', 'email60.com', 'emaildienst.de',
  'emailias.com', 'emailigo.com', 'emailinfive.com', 'emailisvalid.com',
  'emailmiser.com', 'emailsensei.com', 'emailspam.info', 'emailthe.net',
  'emailtmp.com', 'emailwarden.com', 'emailx.at.hm', 'emailxfer.com',
  'emailz.cf', 'emailz.ga', 'emailz.gq', 'emailz.ml', 'emeil.in',
  'emeil.ir', 'emz.net', 'enterto.com', 'ephemail.net', 'etranquil.com',
  'etranquil.net', 'etranquil.org', 'evopo.com', 'example.com',
  'explodemail.com', 'express.net.ua', 'extremail.ru', 'eyepaste.com',
  'facebook-email.cf', 'facebook-email.ga', 'facebook-email.ml',
  'facebookmail.gq', 'facebookmail.ml', 'fake-box.com', 'fake-email.pp.ua',
  'fakemail.fr', 'fakemail.net', 'fakemailz.com', 'fammix.com',
  'fantasymail.de', 'fightallspam.com', 'fiifke.de', 'filzmail.com',
  'fivemail.de', 'fls4.gleeze.com', 'flyspam.com', 'fmailbox.com',
  'fmailc.com', 'frapmail.com', 'free.example.com', 'freemail.ms',
  'freundin.ru', 'friendlymail.co.uk', 'front14.org', 'fudgerub.com',
  'fugglestudios.com', 'fux0ringduh.com', 'fxnxs.com', 'fyii.de',
  'garliclife.com', 'gehensiemirnichtaufdensack.de', 'gelitik.in',
  'get1mail.com', 'get2mail.fr', 'getonemail.com', 'getonemail.net',
  'ghosttexter.de', 'girlsundertheinfluence.com', 'gishpuppy.com',
  'glutenfreemail.com', 'go2usa.info', 'goemailgo.com', 'gorillaswithdirtyarmpits.com',
  'gotmail.com', 'gotmail.net', 'gotmail.org', 'grr.la', 'gsrv.co.uk',
  'gustr.com', 'h.mintemail.com', 'haltospam.com', 'hat-geld.de',
  'hatespam.org', 'herp.in', 'hidemail.de', 'hidzz.com', 'hmamail.com',
  'hopemail.biz', 'hostcalls.com', 'hotpop.com', 'hulapla.de', 'hushmail.com',
  'ieatspam.eu', 'ieatspam.info', 'ieh-mail.de', 'ihateyoualot.info',
  'iheartspam.org', 'imails.info', 'inbax.tk', 'inbox.si', 'inboxalias.com',
  'inboxclean.com', 'inboxclean.org', 'incognitomail.com', 'incognitomail.net',
  'incognitomail.org', 'infogrator.ru', 'inoutmail.de', 'inoutmail.eu',
  'inoutmail.info', 'inoutmail.net', 'insorg-mail.info', 'internet-e-mail.de',
  'internet-mail.de', 'internetemails.net', 'internetmailing.net',
  'inwind.it', 'iplzgo.com', 'irc.so', 'irish2me.com', 'iroid.com',
  'is.afm.student.umm.edu', 'iwi.net', 'jetable.com', 'jetable.de',
  'jetable.eu', 'jetable.fr.nf', 'jetable.net', 'jetable.org',
  'jnxjn.com', 'jourrapide.com', 'jsrsolutions.com', 'junk1.tk',
  'junkmail.ga', 'junkmail.gq', 'jupimail.com', 'kasmail.com',
  'kaspop.com', 'keepmymail.com', 'killmail.com', 'killmail.net',
  'killtimer.com', 'kir.ch.tc', 'klassmaster.com', 'klassmaster.net',
  'klzlk.com', 'kook.ml', 'kosher.pw', 'kpost.be', 'kurzepost.de',
  'l33r.eu', 'lackmail.net', 'lackmail.ru', 'lags.us', 'landmail.co',
  'lastmail.co', 'laurenbt.com', 'lazyinbox.com', 'letthemeatspam.com',
  'lhsdv.com', 'lifebyfood.com', 'link2mail.net', 'litedrop.com',
  'lol.ovpn.to', 'lolfreak.net', 'lookugly.com', 'lortemail.dk',
  'losemymail.com', 'lovemeleaveme.com', 'lr7.us', 'lr78.com',
  'lroid.com', 'lukop.dk', 'm21.cc', 'mail-filter.com', 'mail-temporaire.fr',
  'mail.by', 'mail.mezimages.net', 'mail.zp.ua', 'mail1a.de', 'mail21.cc',
  'mail2rss.org', 'mail333.com', 'mailbucket.org', 'mailcat.biz', 'mailcatch.com',
  'mailde.de', 'mailde.info', 'maildrop.cf', 'maildu.de', 'maileimer.de',
  'mailexpire.com', 'mailfa.tk', 'mailforspam.com', 'mailfreeonline.com',
  'mailguard.me', 'mailin8r.com', 'mailinater.com', 'mailinator.net',
  'mailinator2.com', 'mailincubator.com', 'mailismagic.com', 'mailme.gq',
  'mailme.ir', 'mailme.lv', 'mailme24.com', 'mailmetrash.com',
  'mailmoat.com', 'mailnew.com', 'mailnull.com', 'mailorg.org',
  'mailpick.biz', 'mailproxsy.com', 'mailquack.com', 'mailseal.de',
  'mailshell.com', 'mailsiphon.com', 'mailslapping.com', 'mailslite.com',
  'mailspam.me', 'mailspam.xyz', 'mailsponge.com', 'mailtemp.info',
  'mailtome.de', 'mailtothis.com', 'mailtrash.net', 'mailtv.net',
  'mailtv.tv', 'mailzilla.com', 'makemetheking.com', 'manybrain.com',
  'mbx.cc', 'mega.zik.dj', 'meinspamschutz.de', 'meltmail.com',
  'messagebeamer.de', 'messwiththebestdieliketherest.com', 'mezimages.net',
  'mfsa.ru', 'mierdamail.com', 'migmail.net', 'migmail.pl', 'migumail.com',
  'mintemail.com', 'misterpinball.de', 'mjukglass.nu', 'moakt.com',
  'moakt.cc', 'moakt.co', 'moakt.ws', 'mohmal.com', 'motormania.com.ua',
  'mozartmail.com', 'msa.minsmail.com', 'msgos.com', 'mt2009.com',
  'mt2014.com', 'mucincanon.com', 'mucke-spam.de', 'mungbeansoup.com',
  'myfastmail.com', 'mymail-in.net', 'mymailto.com', 'mynetstore.de',
  'myopmail.com', 'myspaceinc.com', 'myspaceinc.net', 'myspaceinc.org',
  'myspacepimps.net', 'myspamless.com', 'mytrashmail.com', 'mytrashmail.net',
  'mytrashmail.org', 'nabuma.com', 'nada.email', 'nada.ltd',
  'netmails.com', 'netmails.net', 'netzidiot.de', 'neuf.net',
  'newfastmail.com', 'nextmail.ru', 'nice-4u.com', 'nincsmail.com',
  'nk2x2.info', 'nnot.net', 'no-spam.ws', 'no.internet.lu',
  'noblepioneer.com', 'nobulk.com', 'noclickemail.com', 'nogmailspam.info',
  'nospam.ze.tc', 'nospam4.us', 'nospamfor.us', 'nospammail.net',
  'nospamthanks.info', 'notmailinator.com', 'notsharingmy.info',
  'nowhere.org', 'nowmymail.com', 'nowmymail.net', 'nwldx.com',
  'objectmail.com', 'obobbo.com', 'odaymail.com', 'odnorazovoe.ru',
  'ohaaa.de', 'omail.pro', 'oneoffemail.com', 'onewaymail.com',
  'onlatedotcom.info', 'onmail.com', 'online.ms', 'oopi.org',
  'opayq.com', 'ordinaryamerican.net', 'otherinbox.com', 'ourklips.com',
  'ourpreviewdomain.com', 'outblaze.com', 'owlpic.com', 'pancakemail.com',
  'paplease.com', 'pcusers.otherinbox.com', 'pepbot.com', 'pjjkp.com',
  'plexolan.de', 'pm.me', 'pmp.com', 'podzone.net', 'podzone.org',
  'pojisteni.com', 'politikerclub.de', 'poofy.org', 'pookmail.com',
  'pop3.xyz', 'postacin.com', 'privacy.net', 'privatdemail.net',
  'privy-mail.com', 'privy-mail.de', 'proxymail.eu', 'prtnx.com',
  'prtz.eu', 'pubmail.io', 'punkass.com', 'qipmail.net', 'qq.com',
  'qsl.ro', 'quickinbox.com', 'quickmail.in', 'rcpt.at', 'reallymymail.com',
  'recode.me', 'recursor.net', 'recycler.com', 'redpeanut.com',
  'regbypass.com', 'regbypass.comsafe-mail.net', 'rejo.technology',
  'reliable-mail.com', 'rejectmail.com', 'rklips.com', 'rmqkr.net',
  'rn.com', 'robot-mail.com', 'rottemail.de', 'roughnet.com', 'rppkn.com',
  'rtrtr.com', 'ru.nf', 'ruffrey.com', 'rumgel.com', 'ruu.kr',
  'safetymail.info', 'safetypost.de', 'sandelf.de', 'sanfinder.com',
  'saynotospams.com', 'scatmail.com', 'schafmail.de', 'schrott-email.de',
  'secretemail.de', 'secure-mail.biz', 'secure-mail.cc', 'selfdestructingmail.com',
  'sendspamhere.com', 'senseless-entertainment.com', 'services391.com',
  'sharklasers.com', 'sharedmailbox.org', 'shiftmail.com', 'shitmail.de',
  'shitmail.me', 'shitmail.org', 'shitware.nl', 'shmeriously.com',
  'shortmail.net', 'shut.name', 'shut.ws', 'sibmail.com', 'sinnlos-mail.de',
  'skeefmail.com', 'slapsfromlastnight.com', 'slaskpost.se', 'slave-auctions.net',
  'slippery.email', 'slopsbox.com', 'smellfear.com', 'smwg.info',
  'spamavert.com', 'spambob.com', 'spambob.net', 'spambob.org',
  'spambog.com', 'spambog.de', 'spambog.ru', 'spambox.info', 'spambox.irishspringrealty.com',
  'spambox.us', 'spamcannon.com', 'spamcannon.net', 'spamcero.com',
  'spamcon.org', 'spamcorptastic.com', 'spamcowboy.com', 'spamcowboy.net',
  'spamcowboy.org', 'spamday.com', 'spamdecoy.net', 'spame.com',
  'spamex.com', 'spamfree.eu', 'spamfree24.com', 'spamfree24.de',
  'spamfree24.eu', 'spamfree24.info', 'spamfree24.net', 'spamfree24.org',
  'spamgoes.in', 'spamgourmet.com', 'spamgourmet.net', 'spamgourmet.org',
  'spamherelots.com', 'spamhereplease.com', 'spamhole.com', 'spamify.com',
  'spaminator.de', 'spamkill.info', 'spaml.com', 'spaml.de',
  'spammotel.com', 'spammy.host', 'spamoff.de', 'spamsalad.in',
  'spamslicer.com', 'spamspot.com', 'spamstack.net', 'spamthis.co.uk',
  'spamthisplease.com', 'spamtrail.com', 'spamtroll.net', 'speed.1s.fr',
  'spikio.com', 'spils.com', 'spinfinder.com', 'spoofmail.de',
  'squizzy.de', 'squizzy.eu', 'squizzy.net', 'stinkefinger.net',
  'stopspam.org', 'streetwisemail.com', 'stumpfwerk.com', 'suburbanthug.com',
  'super-auswahl.de', 'suremail.info', 'sweetxxx.de', 'tafmail.com',
  'tagyourself.com', 'talkinator.com', 'tapchicuoihoi.com', 'teewars.org',
  'teleworm.com', 'teleworm.us', 'temp-mail.ru', 'tempail.com',
  'tempalias.com', 'tempe-mail.com', 'tempemailaddress.com', 'tempinbox.com',
  'tempinbox.co.uk', 'tempmail.de', 'tempmail.eu', 'tempmail.it',
  'tempmail.net', 'tempmail.org', 'tempmail.us', 'tempmail2.com',
  'tempomail.fr', 'temporarioemail.com.br', 'temporaryemail.net', 'temporaryemail.us',
  'temporaryforwarding.com', 'temporaryinbox.com', 'temporarymailaddress.com',
  'tempsky.com', 'tempthe.net', 'thanksnospam.info', 'thc.st',
  'thelimestones.com', 'thisisnotmyrealemail.com', 'throam.com',
  'throwam.com', 'throwaway.email', 'throwaways.net', 'throwjunk.com',
  'tilien.com', 'tmailinator.com', 'toiea.com', 'tookmsek.com',
  'topranklist.de', 'tormail.net', 'tormail.org', 'tradermail.info',
  'trash-amil.com', 'trash-mail.at', 'trash-mail.com', 'trash-mail.de',
  'trash-mail.ga', 'trash-mail.io', 'trash-mail.tk', 'trash2009.com',
  'trash2010.com', 'trash2011.com', 'trashemail.de', 'trashemails.de',
  'trashimail.de', 'trashinbox.com', 'trashmail.at', 'trashmail.com',
  'trashmail.de', 'trashmail.eu', 'trashmail.io', 'trashmail.me',
  'trashmail.net', 'trashmail.org', 'trashmailer.com', 'trashpanda.com',
  'trbvm.com', 'trbvn.com', 'tretmail.ru', 'trickmail.net',
  'trillianpro.com', 'tryalert.com', 'turual.com', 'twinmail.de',
  'tyldd.com', 'uggsrock.com', 'ultrada.ru', 'umail.net',
  'unmail.ru', 'uroid.com', 'utemail.net', 'uu.gl', 'valemail.net',
  'venompen.com', 'veryday.ch', 'veryday.eu', 'veryday.info', 'veryday.net',
  'veryrealemail.com', 'victoriantwins.com', 'viditag.com', 'viewcastmedia.com',
  'viewcastmedia.net', 'viewcastmedia.org', 'viralplays.com', 'vomoto.com',
  'vpn.st', 'vsimcard.com', 'vubby.com', 'walala.org', 'walkmail.net',
  'walkmail.ru', 'wam.co.za', 'watchfull.net', 'watchme24.com',
  'wbdev.tech', 'webemail.me', 'webm4il.info', 'weedmail.com',
  'wegwerfmail.de', 'wegwerfmail.net', 'wegwerfmail.org', 'wetrainbayarea.com',
  'wetrainbayarea.org', 'whitebot.org', 'whyspam.me', 'wilemail.com',
  'willhackforfood.biz', 'willselfdestruct.com', 'winemaven.info', 'wmail.cf',
  'wolfsmail.tk', 'woofit.com', 'worldemailer.com', 'wuzupmail.net',
  'wwwnew.eu', 'xagloo.co', 'xagloo.com', 'xemaps.com', 'xents.com',
  'xmaily.com', 'xoxy.net', 'xpectmore.com', 'xsmail.com', 'xww.ro',
  'xyzfree.net', 'yapped.net', 'ycare.de', 'ye.vc', 'yep.it',
  'yogamaven.com', 'yopmail.net', 'yopmail.pp.ua', 'yoru-dea.com',
  'youam.de', 'youmail.ga', 'youmailr.com', 'yourweirdfriend.com',
  'youtrashmail.com', 'yuurok.com', 'z1p.biz', 'za.com', 'zain.site',
  'zap-email.com', 'zehnminuten.de', 'zehnminutenmail.de', 'zetmail.com',
  'zippymail.info', 'zoaxe.com', 'zoemail.com', 'zoemail.net',
  'zoemail.org', 'zomg.info', 'zxcv.com', 'zxcvbnm.com', 'zzz.com'
]);

export function isDisposableEmail(email: string): boolean {
  const domain = email.toLowerCase().split('@')[1];
  return DISPOSABLE_DOMAINS.has(domain);
}

export async function hasMxRecords(email: string): Promise<boolean> {
  const domain = email.toLowerCase().split('@')[1];
  if (!domain) return false;
  try {
    const records = await resolveMx(domain);
    return records && records.length > 0;
  } catch {
    return false;
  }
}

export function isValidEmailFormat(email: string): boolean {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  return emailRegex.test(email);
}

export async function validateEmail(email: string): Promise<{ valid: boolean; reason?: string }> {
  if (!isValidEmailFormat(email)) {
    return { valid: false, reason: 'Invalid email format' };
  }
  if (isDisposableEmail(email)) {
    return { valid: false, reason: 'Disposable email addresses are not allowed' };
  }
  const hasMx = await hasMxRecords(email);
  if (!hasMx) {
    return { valid: false, reason: 'Email domain does not exist or cannot receive emails' };
  }
  return { valid: true };
}
